---
- hosts: masters
  gather_facts: false
  tasks:

    - name: Check if master is active
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeconfig

    - name: Create master groups based on status
      group_by: key="{{ 'masters_active' if kubeconfig.stat.exists else 'masters_joining' }}"

    - name: Fail if no active hosts are available
      fail:
        msg: No active hosts available
      when: groups.masters_active is not defined

- hosts: masters_active[0]
  become: yes
  become_user: root
  gather_facts: false
  tasks:

    - name: Get join token
      command: kubeadm token create
      register: string_result

    - name: Store join token
      set_fact:
        join_token: "{{ string_result.stdout }}"

    - name: Get CA key hash
      shell: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'"
      register: string_result

    - name: Store CA key hash
      set_fact:
        ca_key_hash: "{{ string_result.stdout }}"

    - name: Upload certificates
      when: groups.masters | count > 1
      command: kubeadm init phase upload-certs --config=/etc/kubeadm/kubeadm-config.yaml --upload-certs
      register: cert_upload

    - name: Store certificate key
      when: groups.masters | count > 1
      set_fact:
        cert_key: "{{ cert_upload.stdout_lines | last }}"

    # TODO: Remove when dropping support for Kubernetes v1.17
    # Workaround for joining a v1.17 cluster using Kubeadm v1.18:
    # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#not-possible-to-join-a-v1-18-node-to-a-v1-17-cluster-due-to-missing-rbac
    - name: Get Kubeadm version
      shell: kubeadm version -o short
      register: kubeadm_version
    - name: Kubeadm v1.17 -> v1.18 workaround - upload
      copy:
        src: "files/kubeadm-v1.18-hotfix.yaml"
        dest: /etc/kubeadm/kubeadm-v1.18-hotfix.yaml
      when: kubeadm_version.stdout is match("v1.17.*")
    - name: Kubeadm v1.17 -> v1.18 workaround - apply
      command: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f /etc/kubeadm/kubeadm-v1.18-hotfix.yaml
      when: kubeadm_version.stdout is match("v1.17.*")

- hosts: masters_joining
  become: yes
  become_user: root
  gather_facts: false
  serial: 1
  tasks:

    - name: Render kubeadm join config
      template:
        src: kubeadm-join-master.yaml.j2
        dest: /etc/kubeadm/kubeadm-join-master.yaml

    - name: Join the cluster
      command: "kubeadm join --config /etc/kubeadm/kubeadm-join-master.yaml"
      args:
        creates: /etc/kubernetes/kubelet.conf

- hosts: workers
  become: yes
  become_user: root
  gather_facts: false
  tasks:

    - name: Render kubeadm join config
      template:
        src: kubeadm-join.yaml.j2
        dest: /etc/kubeadm/kubeadm-join.yaml

    - name: Join the cluster
      command: "kubeadm join --config /etc/kubeadm/kubeadm-join.yaml"
      args:
        creates: /etc/kubernetes/kubelet.conf

    - name: Render azure config for api-server
      template:
        src: azure.json.j2
        dest: /etc/kubernetes/azure.json
        owner: root
        group: root
        mode: '0644'
      when: cloud_provider is defined and cloud_provider == "azure"
